/*
 * Generated by gdbus-codegen 2.40.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __NMDBUS_DHCP4_CONFIG_H__
#define __NMDBUS_DHCP4_CONFIG_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.freedesktop.NetworkManager.DHCP4Config */

#define NMDBUS_TYPE_DHCP4_CONFIG (nmdbus_dhcp4_config_get_type ())
#define NMDBUS_DHCP4_CONFIG(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), NMDBUS_TYPE_DHCP4_CONFIG, NMDBusDHCP4Config))
#define NMDBUS_IS_DHCP4_CONFIG(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), NMDBUS_TYPE_DHCP4_CONFIG))
#define NMDBUS_DHCP4_CONFIG_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), NMDBUS_TYPE_DHCP4_CONFIG, NMDBusDHCP4ConfigIface))

struct _NMDBusDHCP4Config;
typedef struct _NMDBusDHCP4Config NMDBusDHCP4Config;
typedef struct _NMDBusDHCP4ConfigIface NMDBusDHCP4ConfigIface;

struct _NMDBusDHCP4ConfigIface
{
  GTypeInterface parent_iface;


  GVariant * (*get_options) (NMDBusDHCP4Config *object);

  void (*properties_changed) (
    NMDBusDHCP4Config *object,
    GVariant *arg_properties);

};

GType nmdbus_dhcp4_config_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *nmdbus_dhcp4_config_interface_info (void);
guint nmdbus_dhcp4_config_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus signal emissions functions: */
void nmdbus_dhcp4_config_emit_properties_changed (
    NMDBusDHCP4Config *object,
    GVariant *arg_properties);



/* D-Bus property accessors: */
GVariant *nmdbus_dhcp4_config_get_options (NMDBusDHCP4Config *object);
GVariant *nmdbus_dhcp4_config_dup_options (NMDBusDHCP4Config *object);
void nmdbus_dhcp4_config_set_options (NMDBusDHCP4Config *object, GVariant *value);


/* ---- */

#define NMDBUS_TYPE_DHCP4_CONFIG_PROXY (nmdbus_dhcp4_config_proxy_get_type ())
#define NMDBUS_DHCP4_CONFIG_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), NMDBUS_TYPE_DHCP4_CONFIG_PROXY, NMDBusDHCP4ConfigProxy))
#define NMDBUS_DHCP4_CONFIG_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), NMDBUS_TYPE_DHCP4_CONFIG_PROXY, NMDBusDHCP4ConfigProxyClass))
#define NMDBUS_DHCP4_CONFIG_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), NMDBUS_TYPE_DHCP4_CONFIG_PROXY, NMDBusDHCP4ConfigProxyClass))
#define NMDBUS_IS_DHCP4_CONFIG_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), NMDBUS_TYPE_DHCP4_CONFIG_PROXY))
#define NMDBUS_IS_DHCP4_CONFIG_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), NMDBUS_TYPE_DHCP4_CONFIG_PROXY))

typedef struct _NMDBusDHCP4ConfigProxy NMDBusDHCP4ConfigProxy;
typedef struct _NMDBusDHCP4ConfigProxyClass NMDBusDHCP4ConfigProxyClass;
typedef struct _NMDBusDHCP4ConfigProxyPrivate NMDBusDHCP4ConfigProxyPrivate;

struct _NMDBusDHCP4ConfigProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  NMDBusDHCP4ConfigProxyPrivate *priv;
};

struct _NMDBusDHCP4ConfigProxyClass
{
  GDBusProxyClass parent_class;
};

GType nmdbus_dhcp4_config_proxy_get_type (void) G_GNUC_CONST;

void nmdbus_dhcp4_config_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
NMDBusDHCP4Config *nmdbus_dhcp4_config_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
NMDBusDHCP4Config *nmdbus_dhcp4_config_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void nmdbus_dhcp4_config_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
NMDBusDHCP4Config *nmdbus_dhcp4_config_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
NMDBusDHCP4Config *nmdbus_dhcp4_config_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define NMDBUS_TYPE_DHCP4_CONFIG_SKELETON (nmdbus_dhcp4_config_skeleton_get_type ())
#define NMDBUS_DHCP4_CONFIG_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), NMDBUS_TYPE_DHCP4_CONFIG_SKELETON, NMDBusDHCP4ConfigSkeleton))
#define NMDBUS_DHCP4_CONFIG_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), NMDBUS_TYPE_DHCP4_CONFIG_SKELETON, NMDBusDHCP4ConfigSkeletonClass))
#define NMDBUS_DHCP4_CONFIG_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), NMDBUS_TYPE_DHCP4_CONFIG_SKELETON, NMDBusDHCP4ConfigSkeletonClass))
#define NMDBUS_IS_DHCP4_CONFIG_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), NMDBUS_TYPE_DHCP4_CONFIG_SKELETON))
#define NMDBUS_IS_DHCP4_CONFIG_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), NMDBUS_TYPE_DHCP4_CONFIG_SKELETON))

typedef struct _NMDBusDHCP4ConfigSkeleton NMDBusDHCP4ConfigSkeleton;
typedef struct _NMDBusDHCP4ConfigSkeletonClass NMDBusDHCP4ConfigSkeletonClass;
typedef struct _NMDBusDHCP4ConfigSkeletonPrivate NMDBusDHCP4ConfigSkeletonPrivate;

struct _NMDBusDHCP4ConfigSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  NMDBusDHCP4ConfigSkeletonPrivate *priv;
};

struct _NMDBusDHCP4ConfigSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType nmdbus_dhcp4_config_skeleton_get_type (void) G_GNUC_CONST;

NMDBusDHCP4Config *nmdbus_dhcp4_config_skeleton_new (void);


G_END_DECLS

#endif /* __NMDBUS_DHCP4_CONFIG_H__ */
