/*
 * Generated by gdbus-codegen 2.40.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __NMDBUS_IP4_CONFIG_H__
#define __NMDBUS_IP4_CONFIG_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.freedesktop.NetworkManager.IP4Config */

#define NMDBUS_TYPE_IP4_CONFIG (nmdbus_ip4_config_get_type ())
#define NMDBUS_IP4_CONFIG(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), NMDBUS_TYPE_IP4_CONFIG, NMDBusIP4Config))
#define NMDBUS_IS_IP4_CONFIG(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), NMDBUS_TYPE_IP4_CONFIG))
#define NMDBUS_IP4_CONFIG_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), NMDBUS_TYPE_IP4_CONFIG, NMDBusIP4ConfigIface))

struct _NMDBusIP4Config;
typedef struct _NMDBusIP4Config NMDBusIP4Config;
typedef struct _NMDBusIP4ConfigIface NMDBusIP4ConfigIface;

struct _NMDBusIP4ConfigIface
{
  GTypeInterface parent_iface;


  GVariant * (*get_address_data) (NMDBusIP4Config *object);

  GVariant * (*get_addresses) (NMDBusIP4Config *object);

  const gchar *const * (*get_domains) (NMDBusIP4Config *object);

  const gchar * (*get_gateway) (NMDBusIP4Config *object);

  GVariant * (*get_nameservers) (NMDBusIP4Config *object);

  GVariant * (*get_route_data) (NMDBusIP4Config *object);

  GVariant * (*get_routes) (NMDBusIP4Config *object);

  const gchar *const * (*get_searches) (NMDBusIP4Config *object);

  GVariant * (*get_wins_servers) (NMDBusIP4Config *object);

  void (*properties_changed) (
    NMDBusIP4Config *object,
    GVariant *arg_properties);

};

GType nmdbus_ip4_config_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *nmdbus_ip4_config_interface_info (void);
guint nmdbus_ip4_config_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus signal emissions functions: */
void nmdbus_ip4_config_emit_properties_changed (
    NMDBusIP4Config *object,
    GVariant *arg_properties);



/* D-Bus property accessors: */
GVariant *nmdbus_ip4_config_get_addresses (NMDBusIP4Config *object);
GVariant *nmdbus_ip4_config_dup_addresses (NMDBusIP4Config *object);
void nmdbus_ip4_config_set_addresses (NMDBusIP4Config *object, GVariant *value);

GVariant *nmdbus_ip4_config_get_address_data (NMDBusIP4Config *object);
GVariant *nmdbus_ip4_config_dup_address_data (NMDBusIP4Config *object);
void nmdbus_ip4_config_set_address_data (NMDBusIP4Config *object, GVariant *value);

const gchar *nmdbus_ip4_config_get_gateway (NMDBusIP4Config *object);
gchar *nmdbus_ip4_config_dup_gateway (NMDBusIP4Config *object);
void nmdbus_ip4_config_set_gateway (NMDBusIP4Config *object, const gchar *value);

GVariant *nmdbus_ip4_config_get_routes (NMDBusIP4Config *object);
GVariant *nmdbus_ip4_config_dup_routes (NMDBusIP4Config *object);
void nmdbus_ip4_config_set_routes (NMDBusIP4Config *object, GVariant *value);

GVariant *nmdbus_ip4_config_get_route_data (NMDBusIP4Config *object);
GVariant *nmdbus_ip4_config_dup_route_data (NMDBusIP4Config *object);
void nmdbus_ip4_config_set_route_data (NMDBusIP4Config *object, GVariant *value);

GVariant *nmdbus_ip4_config_get_nameservers (NMDBusIP4Config *object);
GVariant *nmdbus_ip4_config_dup_nameservers (NMDBusIP4Config *object);
void nmdbus_ip4_config_set_nameservers (NMDBusIP4Config *object, GVariant *value);

const gchar *const *nmdbus_ip4_config_get_domains (NMDBusIP4Config *object);
gchar **nmdbus_ip4_config_dup_domains (NMDBusIP4Config *object);
void nmdbus_ip4_config_set_domains (NMDBusIP4Config *object, const gchar *const *value);

const gchar *const *nmdbus_ip4_config_get_searches (NMDBusIP4Config *object);
gchar **nmdbus_ip4_config_dup_searches (NMDBusIP4Config *object);
void nmdbus_ip4_config_set_searches (NMDBusIP4Config *object, const gchar *const *value);

GVariant *nmdbus_ip4_config_get_wins_servers (NMDBusIP4Config *object);
GVariant *nmdbus_ip4_config_dup_wins_servers (NMDBusIP4Config *object);
void nmdbus_ip4_config_set_wins_servers (NMDBusIP4Config *object, GVariant *value);


/* ---- */

#define NMDBUS_TYPE_IP4_CONFIG_PROXY (nmdbus_ip4_config_proxy_get_type ())
#define NMDBUS_IP4_CONFIG_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), NMDBUS_TYPE_IP4_CONFIG_PROXY, NMDBusIP4ConfigProxy))
#define NMDBUS_IP4_CONFIG_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), NMDBUS_TYPE_IP4_CONFIG_PROXY, NMDBusIP4ConfigProxyClass))
#define NMDBUS_IP4_CONFIG_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), NMDBUS_TYPE_IP4_CONFIG_PROXY, NMDBusIP4ConfigProxyClass))
#define NMDBUS_IS_IP4_CONFIG_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), NMDBUS_TYPE_IP4_CONFIG_PROXY))
#define NMDBUS_IS_IP4_CONFIG_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), NMDBUS_TYPE_IP4_CONFIG_PROXY))

typedef struct _NMDBusIP4ConfigProxy NMDBusIP4ConfigProxy;
typedef struct _NMDBusIP4ConfigProxyClass NMDBusIP4ConfigProxyClass;
typedef struct _NMDBusIP4ConfigProxyPrivate NMDBusIP4ConfigProxyPrivate;

struct _NMDBusIP4ConfigProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  NMDBusIP4ConfigProxyPrivate *priv;
};

struct _NMDBusIP4ConfigProxyClass
{
  GDBusProxyClass parent_class;
};

GType nmdbus_ip4_config_proxy_get_type (void) G_GNUC_CONST;

void nmdbus_ip4_config_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
NMDBusIP4Config *nmdbus_ip4_config_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
NMDBusIP4Config *nmdbus_ip4_config_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void nmdbus_ip4_config_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
NMDBusIP4Config *nmdbus_ip4_config_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
NMDBusIP4Config *nmdbus_ip4_config_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define NMDBUS_TYPE_IP4_CONFIG_SKELETON (nmdbus_ip4_config_skeleton_get_type ())
#define NMDBUS_IP4_CONFIG_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), NMDBUS_TYPE_IP4_CONFIG_SKELETON, NMDBusIP4ConfigSkeleton))
#define NMDBUS_IP4_CONFIG_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), NMDBUS_TYPE_IP4_CONFIG_SKELETON, NMDBusIP4ConfigSkeletonClass))
#define NMDBUS_IP4_CONFIG_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), NMDBUS_TYPE_IP4_CONFIG_SKELETON, NMDBusIP4ConfigSkeletonClass))
#define NMDBUS_IS_IP4_CONFIG_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), NMDBUS_TYPE_IP4_CONFIG_SKELETON))
#define NMDBUS_IS_IP4_CONFIG_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), NMDBUS_TYPE_IP4_CONFIG_SKELETON))

typedef struct _NMDBusIP4ConfigSkeleton NMDBusIP4ConfigSkeleton;
typedef struct _NMDBusIP4ConfigSkeletonClass NMDBusIP4ConfigSkeletonClass;
typedef struct _NMDBusIP4ConfigSkeletonPrivate NMDBusIP4ConfigSkeletonPrivate;

struct _NMDBusIP4ConfigSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  NMDBusIP4ConfigSkeletonPrivate *priv;
};

struct _NMDBusIP4ConfigSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType nmdbus_ip4_config_skeleton_get_type (void) G_GNUC_CONST;

NMDBusIP4Config *nmdbus_ip4_config_skeleton_new (void);


G_END_DECLS

#endif /* __NMDBUS_IP4_CONFIG_H__ */
